# Generated by Django 4.2 on 2024-08-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_ENVIA_YA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='sede_principal',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contrasenia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
